In [1]:
import pandas as pd

In [2]:
df_sucio = pd.read_csv('/content/precios_competencia_profeco.csv')

df_sucio.head()

,producto,tipo_producto,precio,fecha_observacion,cadena_comercial,establecimiento,direccion,colonia,cp,municipio,entidad
0,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL GIRASOLES,"RANCHO SAN LORENZO 6, ESQ. CALZADA DE LAS BOMB...",GIRASOLES III,4920,Coyoacán,Ciudad de México
1,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL GIRASOLES,"RANCHO SAN LORENZO 6, ESQ. CALZADA DE LAS BOMB...",GIRASOLES III,4920,Coyoacán,Ciudad de México
2,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,62.0,2026-04-29,MERCADO PUBLICO,MERCADO MIGUEL HIDALGO,"BLVD. SANCHEZ TABOADA 9351, ENTRE CALZ. INDEPE...",ZONA RIO TIJUANA,22010,Tijuana,Baja California
3,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,62.0,2026-04-29,MERCADO PUBLICO,MERCADO MIGUEL HIDALGO,"BLVD. SANCHEZ TABOADA 9351, ENTRE CALZ. INDEPE...",ZONA RIO TIJUANA,22010,Tijuana,Baja California
4,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,54.0,2026-04-29,CHEDRAUI,CHEDRAUI SUCURSAL LEÓN POLIFORUM,"BLVD. FRANCISCO VILLA 105, ESQ. BLVD. ADOLFO L...",EL TLACOACHE,37500,León,Guanajuato

In [18]:
df_sucio.tail()

,producto,tipo_producto,precio,fecha_observacion,cadena_comercial,establecimiento,direccion,colonia,cp,municipio,entidad
1861,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,68.0,2026-06-03,HIPERMERCADO SORIANA,MEGA SORIANA SUCURSAL GUADALAJARA,"RAFAEL SANCIO 55, ENTRE DEBUSSY Y JUAN SEBASTI...",RESIDENCIAL LA ESTANCIA,45030,Zapopan,Jalisco
1862,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,54.5,2026-06-03,MEGA SORIANA,MEGA SORIANA SUCURSAL COACALCO,"LOPEZ PORTILLO 37, ESQ. ENTRADA TULTEPEC",PERIODISTAS,55700,Coacalco,Estado de México
1863,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,48.9,2026-06-03,MERCADO SORIANA,MERCADO SORIANA SUCURSAL SAN LORENZO XALPA (986),"AV. SAN LORENZO 2171, ENTRE NAUTLA Y ESTRELLA",SAN JUAN XALPA,9850,Iztapalapa,Ciudad de México
1864,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,90.0,2026-06-03,MERCADO PUBLICO,MERCADO HIDALGO,"PALMERAS S/N, ESQ. EMILIO CARRANZA",REFORMA,68000,Oaxaca,Oaxaca
1865,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-06-03,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL PORTAL CHURUBUSCO,"AV. RIO CHURUBUSCO 583, ESQ. LA VIGA",SECTOR POPULAR,9060,Iztapalapa,Ciudad de México

In [12]:
print(f'Se van a analizar {df_sucio.shape[0]} registros')
print('---' * 10)

#duplicados
print('Analizamos los datos duplicados')
print('---' * 10)
total_duplicados = df_sucio.duplicated().sum()
print(f"Total de filas duplicadas: {total_duplicados}")

df_sin_dupes = df_sucio.drop_duplicates()
print(f"Total de filas sin duplicados: {df_sin_dupes.shape[0]}")

porcentaje = (total_duplicados / df_sucio.shape[0]) * 100
print(f"Porcentaje de filas duplicadas: {porcentaje:.2f}%")

pct_retencion = 100 - porcentaje
print(f"Porcentaje de filas retenidas: {pct_retencion:.2f}%")

Se van a analizar 1866 registros
------------------------------
Analizamos los datos duplicados
------------------------------
Total de filas duplicadas: 858
Total de filas sin duplicados: 1008
Porcentaje de filas duplicadas: 45.98%
Porcentaje de filas retenidas: 54.02%

In [13]:
print(f'Los tipos de datos son: \n{df_sin_dupes.dtypes}')

Los tipos de datos son:
producto              object
tipo_producto         object
precio               float64
fecha_observacion     object
cadena_comercial      object
establecimiento       object
direccion             object
colonia               object
cp                     int64
municipio             object
entidad               object
dtype: object

In [16]:
#Cambiamos el formato a Date

df_sin_dupes['fecha_observacion'] = pd.to_datetime(df_sin_dupes['fecha_observacion'], errors='coerce')

print(f'Los tipos de datos son: \n{df_sin_dupes.dtypes}')

df_sin_dupes.head()

Los tipos de datos son:
producto                     object
tipo_producto                object
precio                      float64
fecha_observacion    datetime64[ns]
cadena_comercial             object
establecimiento              object
direccion                    object
colonia                      object
cp                            int64
municipio                    object
entidad                      object
dtype: object

/tmp/ipykernel_3871/3270463556.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sin_dupes['fecha_observacion'] = pd.to_datetime(df_sin_dupes['fecha_observacion'], errors='coerce')

,producto,tipo_producto,precio,fecha_observacion,cadena_comercial,establecimiento,direccion,colonia,cp,municipio,entidad
0,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL GIRASOLES,"RANCHO SAN LORENZO 6, ESQ. CALZADA DE LAS BOMB...",GIRASOLES III,4920,Coyoacán,Ciudad de México
2,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,62.0,2026-04-29,MERCADO PUBLICO,MERCADO MIGUEL HIDALGO,"BLVD. SANCHEZ TABOADA 9351, ENTRE CALZ. INDEPE...",ZONA RIO TIJUANA,22010,Tijuana,Baja California
4,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,54.0,2026-04-29,CHEDRAUI,CHEDRAUI SUCURSAL LEÓN POLIFORUM,"BLVD. FRANCISCO VILLA 105, ESQ. BLVD. ADOLFO L...",EL TLACOACHE,37500,León,Guanajuato
6,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,42.8,2026-04-29,MEGA SORIANA,MEGA SORIANA SUCURSAL COAPA,"PROLONGACION DIVISION DEL NORTE1555, ENTRE ESC...",CHIMAL,14700,Tlalpan,Ciudad de México
8,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,42.8,2026-04-29,MERCADO SORIANA,MERCADO SORIANA SUCURSAL LA SIERRA,"CALZ. SILVESTRE TERRAZAS 9001, ENTRE 24 DE FEB...",RAMON REYES,31410,Chihuahua,Chihuahua

In [17]:
df_sin_dupes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1008 entries, 0 to 1833
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   producto           1008 non-null   object
 1   tipo_producto      1008 non-null   object
 2   precio             1008 non-null   float64
 3   fecha_observacion  1008 non-null   datetime64[ns]
 4   cadena_comercial   1008 non-null   object
 5   establecimiento    1008 non-null   object
 6   direccion          1008 non-null   object
 7   colonia            1008 non-null   object
 8   cp                 1008 non-null   int64
 9   municipio          1008 non-null   object
 10  entidad            1008 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 94.5+ KB

In [23]:
#Verificamos si solo tenemos aguacates
no_aguacate = df_sin_dupes[df_sin_dupes['tipo_producto'] != 'AGUACATE']
print('--- Verificando tipos de productos ---')
print(f'Hay {len(no_aguacate)} datos que no son de aguacate')

#verificamos las variedades y presentación de los aguacates
tipos = df_sin_dupes['producto'].unique()
print('--- Verificando tipos y presentaciones de los aguacates ---')
print(f'Hay {len(tipos)} variedades o presentaciones, que son: {tipos}')


#Verificamos los años que hay registrados
anios = df_sin_dupes['fecha_observacion'].dt.year.unique()
print('--- Verificando años ---')
print(f'Hay {len(anios)} años registrados: {anios}')

#observamos las entidades registradas
entidades = df_sin_dupes['entidad'].unique()
print('--- Verificando entidades ---')
print(f'Hay {len(entidades)} entidades registradas: {entidades}')

#Para la cdmx vemos los municipios
cdmx = df_sin_dupes[df_sin_dupes['entidad'] == 'Ciudad de México']
municipios = cdmx['municipio'].unique()
print('--- Verificando municipios ---')
print(f'Hay {len(municipios)} municipios registrados: {municipios}')

--- Verificando tipos de productos ---
Hay 0 datos que no son de aguacate
--- Verificando tipos y presentaciones de los aguacates ---
Hay 1 variedades o presentaciones, que son: ['AGUACATE, S/M, 1 KG. HASS']
--- Verificando años ---
Hay 1 años registrados: [2026]
--- Verificando entidades ---
Hay 30 entidades registradas: ['Ciudad de México' 'Baja California' 'Guanajuato' 'Chihuahua'
 'Estado de México' 'Chiapas' 'Querétaro' 'Tabasco' 'Campeche' 'Coahuila'
 'Quintana Roo' 'Veracruz' 'Jalisco' 'Tlaxcala' 'Sonora' 'Michoacán'
 'Zacatecas' 'Oaxaca' 'Aguascalientes' 'Puebla' 'San Luis Potosí'
 'Sinaloa' 'Baja California Sur' 'Yucatán' 'Guerrero' 'Nuevo León'
 'Durango' 'Morelos' 'Tamaulipas' 'Hidalgo']
--- Verificando municipios ---
Hay 11 municipios registrados: ['Coyoacán' 'Tlalpan' 'Iztapalapa' 'Benito Juárez' 'Miguel Hidalgo'
 'Iztacalco' 'Cuauhtémoc' 'Gustavo A. Madero' 'Venustiano Carranza'
 'Xochimilco' 'Azcapotzalco']

In [24]:
#verificamos nulos por última vez

df_sin_dupes.isna().sum()

producto             0
tipo_producto        0
precio               0
fecha_observacion    0
cadena_comercial     0
establecimiento      0
direccion            0
colonia              0
cp                   0
municipio            0
entidad              0
dtype: int64

In [25]:
#Reporte final
totales = df_sucio.shape[0]
final = df_sin_dupes.shape[0]
pct_ret = final / totales * 100
print(f'De {totales} registros, quedaron solo {final}')
print(f'El porcentaje de retención es del {round(pct_retencion, 2)}%')

De 1866 registros, quedaron solo 1008
El porcentaje de retención es del 54.02%

In [26]:
df_limpio = df_sin_dupes.sort_values(by='fecha_observacion')

df_limpio.head()

,producto,tipo_producto,precio,fecha_observacion,cadena_comercial,establecimiento,direccion,colonia,cp,municipio,entidad
0,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL GIRASOLES,"RANCHO SAN LORENZO 6, ESQ. CALZADA DE LAS BOMB...",GIRASOLES III,4920,Coyoacán,Ciudad de México
72,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,57.0,2026-04-29,WAL-MART,WALMART SUCURSAL PLAZA ORIENTE,"CANAL DE TEZONTLE 1520, ESQ EJE 5 OTE. ROJO GOMEZ",U.H. CUCHILLA DEL MORAL II,9319,Iztapalapa,Ciudad de México
74,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,54.9,2026-04-29,CHEDRAUI,CHEDRAUI SUCURSAL MINA,FCO. JAVIER MINA S/N ENTRE LAMBERTO CASTELLANO...,CENTRO,86000,Centro,Tabasco
76,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,44.9,2026-04-29,LEY (AUTOSERVICIO),LEY SUCURSAL HIDALGO (1102),"BLVD. HIDALGO 1405, ENTRE BLVD. CAMPESPRE Y DE...",FRACC. DE LOS GOMEZ,37470,León,Guanajuato
78,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,60.0,2026-04-29,MERCADO PUBLICO,MERCADO HIDALGO,"PALMERAS S/N, ESQ. EMILIO CARRANZA",REFORMA,68000,Oaxaca,Oaxaca

In [27]:
#Limitamos a la cdmx

df_cdmx = df_limpio[df_limpio['entidad'] == 'Ciudad de México']

df_cdmx.head()

,producto,tipo_producto,precio,fecha_observacion,cadena_comercial,establecimiento,direccion,colonia,cp,municipio,entidad
0,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL GIRASOLES,"RANCHO SAN LORENZO 6, ESQ. CALZADA DE LAS BOMB...",GIRASOLES III,4920,Coyoacán,Ciudad de México
72,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,57.0,2026-04-29,WAL-MART,WALMART SUCURSAL PLAZA ORIENTE,"CANAL DE TEZONTLE 1520, ESQ EJE 5 OTE. ROJO GOMEZ",U.H. CUCHILLA DEL MORAL II,9319,Iztapalapa,Ciudad de México
82,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,56.0,2026-04-29,CHEDRAUI,CHEDRAUI SUCURSAL PLAZA AMERICA,"BENITO JUAREZ 117, ENTRE DIVISION DEL NORTE Y ...",EXHACIENDA DE COAPA,4850,Coyoacán,Ciudad de México
86,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,59.0,2026-04-29,WAL-MART EXPRESS,WALMART EXPRESS SUCURSAL TAXQUEÑA,"CALZ. TAXQUEÑA 1752, ENTRE PASEO DE LOS JARDIN...",TAXQUEÑA,4280,Coyoacán,Ciudad de México
88,"AGUACATE, S/M, 1 KG. HASS",AGUACATE,55.0,2026-04-29,BODEGA AURRERA,BODEGA AURRERA SUCURSAL LOS ANGELES,"CALZ. ERMITA IZTAPALAPA 2001, ESQ. MARGARITAS",LOS ANGELES,9830,Iztapalapa,Ciudad de México

In [28]:
print(f'Para la cdmx se encontraron {df_cdmx.shape[0]} datos')

Para la cdmx se encontraron 221 datos

In [29]:
#guardamos el df limpio

df_cdmx.to_csv('competencia_cdmx_limpio.csv', index=False, encoding='UTF-8')